version: "3.8"
name: medaid

services:
  medaid:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_GEMINI_API_KEY=""
      - NEXT_PUBLIC_PINATA_JWT=""
      - PRIVATE_KEY=""
      - CONTRACT_ADDRESS=""
      - MONGO_URI=""
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
