version: "3.8"
name: medaid

services:
  medaid:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_GEMINI_API_KEY=AIzaSyCzeU__Ojn6MZLd7ke0aAhH2R34VmI95f4
      - NEXT_PUBLIC_PINATA_JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiIzNGVmMWE4MC1lMjZjLTQyN2QtODhjOS1mNzUzNzRlYTIzZTgiLCJlbWFpbCI6ImtyaXNoc2luZ2hodXJhQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaW5fcG9saWN5Ijp7InJlZ2lvbnMiOlt7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6IkZSQTEifSx7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6Ik5ZQzEifV0sInZlcnNpb24iOjF9LCJtZmFfZW5hYmxlZCI6ZmFsc2UsInN0YXR1cyI6IkFDVElWRSJ9LCJhdXRoZW50aWNhdGlvblR5cGUiOiJzY29wZWRLZXkiLCJzY29wZWRLZXlLZXkiOiJkNWUzNTA1ODk0OWY4YjllODEzYyIsInNjb3BlZEtleVNlY3JldCI6IjRhZDJkMTI2YTMzNzc0MWE4ZmE5ZGQzMjM1YWY2YjU4MTIwZDY1YzA1OTYwYzI4ZmRmOThiZGE1ODA1NmYxMzYiLCJleHAiOjE3NzExNjIxOTZ9.z_SoT_1XIgOpGEFrwqsuhZsorc351bSr_OopFSkjJr8
      - PRIVATE_KEY=7480e9187fdc5829a8aa42c23be080bdbafb69a005a4fd0d57ac90986aca55b2
      - CONTRACT_ADDRESS=0xeb2D76203f73dCe53a59c645C357e9A8B68DB936
      - MONGO_URI=mongodb+srv://krishsinghhura:Krishhura1@cluster0.4tpqd.mongodb.net/medaid?retryWrites=true&w=majority
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
